---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - autoheal.desiredcloud.com
  resources:
  - podrecoveryplans
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - autoheal.desiredcloud.com
  resources:
  - podrecoveryplans/finalizers
  verbs:
  - update
- apiGroups:
  - autoheal.desiredcloud.com
  resources:
  - podrecoveryplans/status
  verbs:
  - get
  - patch
  - update
